In [16]:
import pandas

df=pandas.read_csv('~/Documents/uni/AP1/git/Praktikum-A1/3_31/Measurements/solid/solid_2_cooldown_process.csv', decimal=',',delimiter='\t',header=None, names=['Zeit/s', 'Temperatur/Grad C'])
df.head(n=1000)

       Zeit/s  Temperatur/Grad C
0    9229.720             74.184
1    9230.720             74.074
2    9231.721             73.598
3    9232.721             73.818
4    9233.720             73.744
5    9234.720             73.231
6    9235.720             72.974
7    9236.720             73.084
8    9237.720             72.241
9    9238.720             72.388
10   9239.720             72.278
11   9240.721             72.314
12   9241.721             70.371
13   9242.721             66.850
14   9243.721             63.729
15   9244.721             59.871
16   9245.721             58.068
17   9246.722             56.043
18   9247.723             54.347
19   9248.723             52.871
20   9249.724             51.801
21   9250.725             50.101
22   9251.724             49.731
23   9252.724             48.103
24   9253.725             46.732
25   9254.725             46.213
26   9255.726             45.286
27   9256.727             43.987
28   9257.728             43.615
29   9258.728             43.020
..        ...                ...
126  9355.771             27.374
127  9356.772             27.901
128  9357.773             27.072
129  9358.774             28.128
130  9359.774             27.600
131  9360.774             27.336
132  9361.774             27.788
133  9362.774             26.959
134  9363.774             27.751
135  9364.774             27.298
136  9365.775             27.147
137  9366.776             26.997
138  9367.777             27.524
139  9368.778             27.223
140  9369.778             27.449
141  9370.778             27.374
142  9371.778             27.600
143  9372.777             26.921
144  9373.777             27.110
145  9374.777             27.261
146  9375.778             27.185
147  9376.778             27.185
148  9377.778             27.411
149  9378.779             27.713
150  9379.779             27.411
151  9380.780             27.939
152  9381.780             26.959
153  9382.781             27.449
154  9383.781             26.732
155  9384.782             27.034

[156 rows x 2 columns]

In [11]:
import pandas

df=pandas.read_csv('~/Documents/uni/AP1/git/Praktikum-A1/3_31/Measurements/solid/water_kalorimeter2.csv', decimal=',',delimiter='\t',header=None, names=['Zeit/s', 'Temperatur/Grad C'])
df.head(n=1000)

     Zeit/s  Temperatur/Grad C
0  8477.324             20.413
1  8478.323             20.262
2  8479.323             20.641
3  8480.323             20.186
4  8481.324             19.806
5  8482.324             20.110
6  8483.326             19.920
7  8484.326             19.388
8  8485.326             19.388
9  8486.326             19.844

In [12]:
import pandas

df=pandas.read_csv('~/Documents/uni/AP1/git/Praktikum-A1/3_31/Measurements/kalorimeter/mix.txt', decimal=',',delimiter='\t',header=None, names=['Zeit/s', 'Temperatur/Grad C'])
df.head(n=1000)

       Zeit/s  Temperatur/Grad C
0   10044.577             21.172
1   10045.576             20.793
2   10046.577             20.641
3   10047.578             20.945
4   10048.578             22.309
5   10049.578             64.317
6   10050.578             62.150
7   10051.579             58.326
8   10052.579             55.858
9   10053.579             53.609
10  10054.581             51.542
11  10055.581             50.323
12  10056.582             49.176
13  10057.582             48.473
14  10058.582             47.732
15  10059.581             47.251
16  10060.582             46.695
17  10061.583             47.510
18  10062.583             47.510
19  10063.583             47.103
20  10064.583             47.029
21  10065.584             47.066
22  10066.585             46.843
23  10067.585             46.880
24  10068.585             46.361
25  10069.585             46.917
26  10070.585             47.251
27  10071.585             46.436
28  10072.586             46.695
29  10073.586             46.621
..        ...                ...
48  10092.593             45.916
49  10093.592             46.102
50  10094.592             46.473
51  10095.592             46.139
52  10096.592             46.880
53  10097.592             46.436
54  10098.593             46.361
55  10099.594             45.954
56  10100.594             46.324
57  10101.595             46.658
58  10102.596             45.991
59  10103.596             46.436
60  10104.596             46.658
61  10105.596             46.361
62  10106.596             46.473
63  10107.597             46.176
64  10108.597             46.250
65  10109.598             46.213
66  10110.598             46.621
67  10111.597             46.806
68  10112.597             46.139
69  10113.598             46.065
70  10114.598             46.399
71  10115.598             46.473
72  10116.599             46.176
73  10117.600             46.028
74  10118.600             46.473
75  10119.601             46.361
76  10120.601             46.287
77  10121.601             46.102

[78 rows x 2 columns]

In [26]:
with open ('/home/a/Documents/uni/AP1/git/Praktikum-A1/3_31/Measurements/solid/water_kalorimeter2','r') as myfile:
    data=myfile.read().replace(',','.').replace('\n','\\\\ ').replace('	',' & ')

print(data)

8477.324 & 20.413\\ 8478.323 & 20.262\\ 8479.323 & 20.641\\ 8480.323 & 20.186\\ 8481.324 & 19.806\\ 8482.324 & 20.110\\ 8483.326 & 19.920\\ 8484.326 & 19.388\\ 8485.326 & 19.388\\ 8486.326 & 19.844\\

In [27]:
with open ('/home/a/Documents/uni/AP1/git/Praktikum-A1/3_31/Measurements/solid/solid_2_cooldown_process','r') as myfile:
    data=myfile.read().replace(',','.').replace('\n','\\\\ ').replace('	',' & ')

print(data)

9229.720 & 74.184\\ 9230.720 & 74.074\\ 9231.721 & 73.598\\ 9232.721 & 73.818\\ 9233.720 & 73.744\\ 9234.720 & 73.231\\ 9235.720 & 72.974\\ 9236.720 & 73.084\\ 9237.720 & 72.241\\ 9238.720 & 72.388\\ 9239.720 & 72.278\\ 9240.721 & 72.314\\ 9241.721 & 70.371\\ 9242.721 & 66.850\\ 9243.721 & 63.729\\ 9244.721 & 59.871\\ 9245.721 & 58.068\\ 9246.722 & 56.043\\ 9247.723 & 54.347\\ 9248.723 & 52.871\\ 9249.724 & 51.801\\ 9250.725 & 50.101\\ 9251.724 & 49.731\\ 9252.724 & 48.103\\ 9253.725 & 46.732\\ 9254.725 & 46.213\\ 9255.726 & 45.286\\ 9256.727 & 43.987\\ 9257.728 & 43.615\\ 9258.728 & 43.020\\ 9259.728 & 42.388\\ 9260.729 & 42.054\\ 9261.729 & 41.011\\ 9262.730 & 40.639\\ 9263.730 & 39.894\\ 9264.731 & 39.223\\ 9265.732 & 38.775\\ 9266.733 & 38.626\\ 9267.733 & 38.178\\ 9268.732 & 37.319\\ 9269.732 & 37.357\\ 9270.733 & 36.460\\ 9271.733 & 36.310\\ 9272.734 & 36.534\\ 9273.735 & 35.562\\ 9274.735 & 35.450\\ 9275.736 & 35.075\\ 9276.737 & 34.626\\ 9277.737 & 34.327\\ 9278.737 & 33.914\\ 9279.737 & 34.027\\ 9280.738 & 33.502\\ 9281.739 & 33.764\\ 9282.740 & 33.315\\ 9283.740 & 33.127\\ 9284.740 & 32.752\\ 9285.739 & 33.090\\ 9286.739 & 32.377\\ 9287.740 & 32.264\\ 9288.740 & 31.701\\ 9289.741 & 32.414\\ 9290.741 & 31.814\\ 9291.742 & 31.588\\ 9292.743 & 31.401\\ 9293.744 & 31.025\\ 9294.745 & 30.875\\ 9295.746 & 30.987\\ 9296.746 & 30.724\\ 9297.747 & 31.062\\ 9298.747 & 30.611\\ 9299.749 & 30.348\\ 9300.749 & 30.123\\ 9301.750 & 29.859\\ 9302.750 & 29.897\\ 9303.749 & 30.461\\ 9304.750 & 30.085\\ 9305.751 & 29.709\\ 9306.751 & 30.386\\ 9307.751 & 29.596\\ 9308.751 & 29.483\\ 9309.752 & 29.483\\ 9310.753 & 29.446\\ 9311.754 & 29.446\\ 9312.755 & 30.198\\ 9313.756 & 28.994\\ 9314.757 & 28.617\\ 9315.758 & 28.843\\ 9316.760 & 28.806\\ 9317.760 & 28.467\\ 9318.760 & 28.730\\ 9319.761 & 28.429\\ 9320.760 & 28.504\\ 9321.760 & 28.316\\ 9322.761 & 28.354\\ 9323.762 & 28.354\\ 9324.762 & 28.919\\ 9325.762 & 28.128\\ 9326.763 & 28.580\\ 9327.763 & 28.203\\ 9328.764 & 28.429\\ 9329.765 & 28.203\\ 9330.765 & 27.901\\ 9331.765 & 28.014\\ 9332.766 & 28.128\\ 9333.767 & 28.391\\ 9334.768 & 27.600\\ 9335.768 & 28.128\\ 9336.768 & 27.939\\ 9337.767 & 27.977\\ 9338.768 & 27.864\\ 9339.768 & 27.826\\ 9340.768 & 27.826\\ 9341.768 & 27.524\\ 9342.769 & 27.562\\ 9343.769 & 27.977\\ 9344.769 & 27.298\\ 9345.769 & 27.826\\ 9346.770 & 27.939\\ 9347.770 & 27.751\\ 9348.770 & 27.901\\ 9349.770 & 27.638\\ 9350.770 & 27.147\\ 9351.772 & 27.034\\ 9352.772 & 28.241\\ 9353.772 & 27.600\\ 9354.772 & 27.524\\ 9355.771 & 27.374\\ 9356.772 & 27.901\\ 9357.773 & 27.072\\ 9358.774 & 28.128\\ 9359.774 & 27.600\\ 9360.774 & 27.336\\ 9361.774 & 27.788\\ 9362.774 & 26.959\\ 9363.774 & 27.751\\ 9364.774 & 27.298\\ 9365.775 & 27.147\\ 9366.776 & 26.997\\ 9367.777 & 27.524\\ 9368.778 & 27.223\\ 9369.778 & 27.449\\ 9370.778 & 27.374\\ 9371.778 & 27.600\\ 9372.777 & 26.921\\ 9373.777 & 27.110\\ 9374.777 & 27.261\\ 9375.778 & 27.185\\ 9376.778 & 27.185\\ 9377.778 & 27.411\\ 9378.779 & 27.713\\ 9379.779 & 27.411\\ 9380.780 & 27.939\\ 9381.780 & 26.959\\ 9382.781 & 27.449\\ 9383.781 & 26.732\\ 9384.782 & 27.034\\

In [28]:
with open ('/home/a/Documents/uni/AP1/git/Praktikum-A1/3_31/Measurements/kalorimeter/icewater','r') as myfile:
    data=myfile.read().replace(',','.').replace('\n','\\\\ ').replace('	',' & ')

print(data)

9850.794 & 0.983\\ 9851.793 & 1.787\\ 9852.794 & 1.634\\ 9853.794 & 1.863\\ 9854.794 & 2.284\\ 9855.794 & 2.093\\ 9856.794 & -0.975\\ 9857.794 & 0.715\\ 9858.795 & 1.902\\ 9859.795 & 1.787\\ 9860.795 & 1.174\\ 9861.795 & 1.251\\ 9862.796 & 1.251\\ 9863.797 & 1.557\\ 9864.798 & 1.327\\ 9865.798 & 1.251\\

In [29]:
with open ('/home/a/Documents/uni/AP1/git/Praktikum-A1/3_31/Measurements/kalorimeter/hotwater.txt','r') as myfile:
    data=myfile.read().replace(',','.').replace('\n','\\\\ ').replace('	',' & ')

print(data)

9993.969 & 81.957\\ 9994.969 & 82.214\\ 9995.970 & 81.884\\ 9996.971 & 81.664\\ 9997.972 & 81.957\\ 9998.972 & 82.067\\ 9999.972 & 81.260\\ 10000.973 & 81.847\\ 10001.974 & 81.187\\ 10002.975 & 81.444\\ 10003.977 & 81.223\\ 10004.978 & 80.527\\ 10005.978 & 80.857\\ 10006.977 & 80.160\\ 10007.978 & 80.380\\

In [30]:
with open ('/home/a/Documents/uni/AP1/git/Praktikum-A1/3_31/Measurements/kalorimeter/mix.txt','r') as myfile:
    data=myfile.read().replace(',','.').replace('\n','\\\\ ').replace('	',' & ')

print(data)

10044.577 & 21.172\\ 10045.576 & 20.793\\ 10046.577 & 20.641\\ 10047.578 & 20.945\\ 10048.578 & 22.309\\ 10049.578 & 64.317\\ 10050.578 & 62.150\\ 10051.579 & 58.326\\ 10052.579 & 55.858\\ 10053.579 & 53.609\\ 10054.581 & 51.542\\ 10055.581 & 50.323\\ 10056.582 & 49.176\\ 10057.582 & 48.473\\ 10058.582 & 47.732\\ 10059.581 & 47.251\\ 10060.582 & 46.695\\ 10061.583 & 47.510\\ 10062.583 & 47.510\\ 10063.583 & 47.103\\ 10064.583 & 47.029\\ 10065.584 & 47.066\\ 10066.585 & 46.843\\ 10067.585 & 46.880\\ 10068.585 & 46.361\\ 10069.585 & 46.917\\ 10070.585 & 47.251\\ 10071.585 & 46.436\\ 10072.586 & 46.695\\ 10073.586 & 46.621\\ 10074.587 & 47.066\\ 10075.588 & 46.917\\ 10076.587 & 46.436\\ 10077.587 & 46.917\\ 10078.587 & 46.769\\ 10079.588 & 46.917\\ 10080.588 & 46.547\\ 10081.589 & 46.806\\ 10082.590 & 46.473\\ 10083.591 & 46.473\\ 10084.592 & 46.436\\ 10085.592 & 46.361\\ 10086.592 & 46.510\\ 10087.592 & 46.139\\ 10088.592 & 46.621\\ 10089.593 & 46.176\\ 10090.593 & 46.287\\ 10091.593 & 46.213\\ 10092.593 & 45.916\\ 10093.592 & 46.102\\ 10094.592 & 46.473\\ 10095.592 & 46.139\\ 10096.592 & 46.880\\ 10097.592 & 46.436\\ 10098.593 & 46.361\\ 10099.594 & 45.954\\ 10100.594 & 46.324\\ 10101.595 & 46.658\\ 10102.596 & 45.991\\ 10103.596 & 46.436\\ 10104.596 & 46.658\\ 10105.596 & 46.361\\ 10106.596 & 46.473\\ 10107.597 & 46.176\\ 10108.597 & 46.250\\ 10109.598 & 46.213\\ 10110.598 & 46.621\\ 10111.597 & 46.806\\ 10112.597 & 46.139\\ 10113.598 & 46.065\\ 10114.598 & 46.399\\ 10115.598 & 46.473\\ 10116.599 & 46.176\\ 10117.600 & 46.028\\ 10118.600 & 46.473\\ 10119.601 & 46.361\\ 10120.601 & 46.287\\ 10121.601 & 46.102\\